### ISSUE TITLE
Snapchat won't open, "stops working"

### ISSUE THREAD

**Issue by Crayder** [hashSnap/snapIntercept#1]
The SC app won't open when I have SnapIntercept installed. It forces closed a few seconds into the startup screen.

SC version 10.18.6.0
SCI version 1.0.9
Xposed 88
Android 7.1.2

**Comment by Crayder** [comment]
Okay it worked when you added the 10.18.6.0 update... But now 10.19.0.0 is out and it crashes like before. This mod needs to be more dynamic with the Snapchat version.

**Comment by hashSnap** [comment]
A new release is out, compatible with 10.19.0.0. The crash occurs when you use the wrong combination of Snapchat+Snapintercept. So wait for a Snapintercept update before updating Snapchat.

**Comment by Crayder** [comment]
Like I said...

`This mod needs to be more dynamic with the Snapchat version.`

From what I can see there is no version-specific code besides the version number, so why not make it automatically detect and update the version number or something?

**Comment by Crayder** [comment]
Can we get the latest update? @hashSnap

**Comment by hashSnap** [comment]
Every line of code in Obfuscator.java is version specific and needs to be updated with almost every Snapchat version. The crash was not intended but I will leave it as it's a perfect way to avoid wrong combinations of Snapchat+Snapintercept.

I will try to update the module soon.
